// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpekircyahgagposjaqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwZWtpcmN5YWhnYWdwb3NqYXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTk4OTAsImV4cCI6MjA1NjkzNTg5MH0.dSBvYsLxeZE3ALlxrmU0o7ocqWhvX3hIygER-JUzXek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);