
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riobdleqxspscsobfjdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpb2JkbGVxeHNwc2Nzb2JmamRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDUwOTksImV4cCI6MjA2NjY4MTA5OX0.PKDGvA2WWN16-b-6HvpB7N7cf88ByI8mVFWch8iI-0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
